
[custom_weaponry]

	[custom_weaponry.sample]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, BOW, CROSSBOW
		weapon_type = "SWORD"
		registry_name = "epicfight:registryname"

[custom_armor]

	[custom_armor.sample]
		stun_armor = 0.0
		weight = 0.0
		registry_name = "epicfight:registryname"

